language: python
cache: pip
install:
  - pip install black
  - pip install -r requirements.txt
  - pip install -e '.[build]'
jobs:
  include:
    - stage: "Code Formatting"
      script: black --check --verbose .
    - stage: "Tests"
      name: "Unit Tests"
      script: pytest
