language: python
cache: pip
install:
  - pip install -e '.[build]'
  - pip install -r requirements.txt
jobs:
  include:
    - stage: "Code Formatting"
      install: pip install black
      script: black --check --verbose .
    - stage: "Tests"
      name: "Unit Tests"
      script: pytest
    - stage: "Documentation"
      before_install: pip install sphinx
      before_script: cd docs
      script: make html O=-nW
