language: python
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -e '.[build]'
jobs:
  include:
    - stage: "Code Formatting"
      install: pip install black
      script: black --check --verbose .
    - stage: "Tests"
      name: "Unit Tests"
      script: pytest
      env: OMP_NUM_THREADS=1
    - stage: "Documentation"
      install: pip install sphinx
      before_script: cd docs
      script: make html
