package:
  name: lagrangian-filtering
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_rev: master
  git_url: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - setuptools_scm
  run:
    - python >=3.6
    - dask
    - h5py
    - numpy
    - scipy >=1.2.0
    - parcels

about:
  home: https://github.com/angus-g/lagrangian-filtering
  license: MIT
  license_file: LICENSE
  summary: Temporal filtering of data in a Lagrangian frame of reference
