name: Testing

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0

  testing:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.1.0
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e 'packages/tracking/[test]' -e 'packages/filtering/[test]'
      - name: Type checking
        run: |
          uvx ty check packages/
      - name: Unit tests
        run: |
          uv run pytest
